name: Release

on:
  release:
    types: [published]

jobs:
  build:

    runs-on: ubuntu-latest
    secrets: ["api_key"]
        
    steps:
    - uses: actions/checkout@v1
    - name: Publish
      run: | 
        pwsh -Command "Publish-Module -Path ./Output/Selenium.psd1 -NuGetApiKey $Env:api_key"
        
